
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/grocery?useUnicode=true&characterEncoding=utf8
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: l8036316
  jpa:
    hibernate:
      ddl-auto: update
#    show-sql: true
server:
  port: 8082
